info:
  spring:
    profiles: ${spring.profiles.active:default}

spring:
  profiles:
    active: production

irbis:
  host: 127.0.0.1
  port: 6666
---

spring:
  config:
    activate:
      on-profile: dev

server:
  port: 8081

irbis:
  host: 10.8.1.1
  user: MASTER
  password: MASTERKEY
---

spring:
  config:
    activate:
      on-profile: production

server:
  port: 8081

irbis:
  host: 10.1.1.3
  user: 1
  password: 1
---

spring:
  config:
    activate:
      on-profile: wan

irbis:
  host: 193.110.163.14
---

spring:
  config:
    activate:
      on-profile: lan

irbis:
  host: 10.1.1.123
